/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.example.dominio.Tablero;
import static java.lang.Integer.parseInt;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emanuel-Not
 */
public class JFPrincipal extends javax.swing.JFrame {

    private Tablero tab1;
    private int posCeldaA, posCeldaB, cartasDisp;
    private final int cantCeldas;
    private boolean jugando;
    private final JButton[] jbCartasVisibles = new JButton[2];
    private DefaultTableModel tabla = new DefaultTableModel();

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("MEMORAMA");
        jugando = false;
        cantCeldas = 16;
        String[] columnas = {"Jugador", "Puntaje", "Tiempo", "Intentos"};
        tabla.setColumnIdentifiers(columnas);
    }

    private void iniciaJuego(int tematica) {
        tab1 = new Tablero(tematica, cantCeldas, jtNomJugador.getText());
        tab1.setCartas();
        // Extrae los componentes de jpCeldas (botones), identifica el orden con
        // getName y le asigna la imagen que le corresponde a cada botón.
        JButton jbC = new JButton();
        for (int i = 1; i <= cantCeldas; i++) {
            for (int j = 0; j < cantCeldas; j++) {
                if (i == Integer.parseInt(jpCeldas.getComponent(j).getName())) {
                    jbC = (JButton) jpCeldas.getComponent(j);
                    jbC.setIcon(new ImageIcon(getClass().getResource(tab1.getCartas().get(i - 1).getImgContraCara())));
                    jbC.setDisabledIcon(new ImageIcon(getClass().getResource(tab1.getCartas().get(i - 1).getImgCarta())));
                }
            }
        }
        tab1.setTiempoIni(LocalTime.now());
        //Comienza el juego.
    }

    private void jbEnabled(JButton jb, int posCelda) {
        if (jbCartasVisibles[0] != null && jbCartasVisibles[1] != null) {
            jbCartasVisibles[0].setEnabled(true);
            jbCartasVisibles[1].setEnabled(true);
            jbCartasVisibles[0] = jb;
            posCeldaA = posCelda;
            jb.setEnabled(false);
            jbCartasVisibles[1] = null;
        } else {
            if (jbCartasVisibles[0] == null && jbCartasVisibles[1] == null) {
                jb.setEnabled(false);
                jbCartasVisibles[0] = jb;
                posCeldaA = posCelda;
            } else {
                jb.setEnabled(false);
                jbCartasVisibles[1] = jb;
                posCeldaB = posCelda;
                jlIntentos.setText(String.valueOf(Integer.parseInt(jlIntentos.getText()) + 1));
                // Compara cartas
                if (tab1.comparaCartas(posCeldaA, posCeldaB)) {
                    jbCartasVisibles[0] = null;
                    jbCartasVisibles[1] = null;
                    cartasDisp -= 2;
                    // Suma puntuacion
                    tab1.puntuacion(posCeldaA, posCeldaB);
                    if (cartasDisp == 0) {
                        finalizarJuego();
                    }
                }
            }
        }
    }

    private void finalizarJuego() {
        tab1.setTiempoTranscurrido();
        JOptionPane.showMessageDialog(this, "El juego ha finalizado."
                + tab1.toString(), "\nFELICIDADES!!!", JOptionPane.INFORMATION_MESSAGE);
        rankear();
        jbIniciar.setText("Nueva partida");
        jbIniciar.setMnemonic('N');
        jcbTematica.setEnabled(true);
        jtNomJugador.setEnabled(true);
        jtNomJugador.setText("");
        jugando = false;
    }

    private void rankear() {
        String[] fila = new String[4];
        fila[0] = tab1.getNomJugador();
        fila[1] = String.valueOf(tab1.getPuntaje());
        fila[2] = tab1.getTiempoFin();
        fila[3] = jlIntentos.getText();
        tabla.addRow(fila);
        jtRanking.setModel(tabla);
    }

    private void voltearCartas() {
        JButton jbC = new JButton();
        for (int i = 0; i < cantCeldas; i++) {
            jbC = (JButton) jpCeldas.getComponent(i);
            jbC.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbIniciar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jcbTematica = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRanking = new javax.swing.JTable();
        jpCeldas = new javax.swing.JPanel();
        jbCarta1 = new javax.swing.JButton();
        jbCarta2 = new javax.swing.JButton();
        jbCarta3 = new javax.swing.JButton();
        jbCarta4 = new javax.swing.JButton();
        jbCarta5 = new javax.swing.JButton();
        jbCarta6 = new javax.swing.JButton();
        jbCarta7 = new javax.swing.JButton();
        jbCarta8 = new javax.swing.JButton();
        jbCarta9 = new javax.swing.JButton();
        jbCarta10 = new javax.swing.JButton();
        jbCarta11 = new javax.swing.JButton();
        jbCarta12 = new javax.swing.JButton();
        jbCarta13 = new javax.swing.JButton();
        jbCarta14 = new javax.swing.JButton();
        jbCarta15 = new javax.swing.JButton();
        jbCarta16 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtNomJugador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlIntentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setResizable(false);

        jbIniciar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbIniciar.setMnemonic('N');
        jbIniciar.setText("Nueva Partida");
        jbIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Temática:");

        jcbTematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemáticas", "Banderas", "Shrek" }));

        jtRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Jugador", "Puntaje", "Tiempo", "Intentos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRanking.setEnabled(false);
        jScrollPane1.setViewportView(jtRanking);

        jpCeldas.setBackground(new java.awt.Color(102, 102, 102));

        jbCarta1.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta1.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta1.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta1.setName("1"); // NOI18N
        jbCarta1.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCarta1MouseExited(evt);
            }
        });
        jbCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta1ActionPerformed(evt);
            }
        });

        jbCarta2.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta2.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta2.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta2.setName("2"); // NOI18N
        jbCarta2.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta2ActionPerformed(evt);
            }
        });

        jbCarta3.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta3.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta3.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta3.setName("3"); // NOI18N
        jbCarta3.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta3ActionPerformed(evt);
            }
        });

        jbCarta4.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta4.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta4.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta4.setName("4"); // NOI18N
        jbCarta4.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta4ActionPerformed(evt);
            }
        });

        jbCarta5.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta5.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta5.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta5.setName("5"); // NOI18N
        jbCarta5.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta5ActionPerformed(evt);
            }
        });

        jbCarta6.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta6.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta6.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta6.setName("6"); // NOI18N
        jbCarta6.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta6ActionPerformed(evt);
            }
        });

        jbCarta7.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta7.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta7.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta7.setName("7"); // NOI18N
        jbCarta7.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta7ActionPerformed(evt);
            }
        });

        jbCarta8.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta8.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta8.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta8.setName("8"); // NOI18N
        jbCarta8.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta8ActionPerformed(evt);
            }
        });

        jbCarta9.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta9.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta9.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta9.setName("9"); // NOI18N
        jbCarta9.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta9ActionPerformed(evt);
            }
        });

        jbCarta10.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta10.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta10.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta10.setName("10"); // NOI18N
        jbCarta10.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta10ActionPerformed(evt);
            }
        });

        jbCarta11.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta11.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta11.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta11.setName("11"); // NOI18N
        jbCarta11.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta11ActionPerformed(evt);
            }
        });

        jbCarta12.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta12.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta12.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta12.setName("12"); // NOI18N
        jbCarta12.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta12ActionPerformed(evt);
            }
        });

        jbCarta13.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta13.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta13.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta13.setName("13"); // NOI18N
        jbCarta13.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta13ActionPerformed(evt);
            }
        });

        jbCarta14.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta14.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta14.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta14.setName("14"); // NOI18N
        jbCarta14.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta14ActionPerformed(evt);
            }
        });

        jbCarta15.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta15.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta15.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta15.setName("15"); // NOI18N
        jbCarta15.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta15ActionPerformed(evt);
            }
        });

        jbCarta16.setBackground(new java.awt.Color(204, 204, 255));
        jbCarta16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cMath.png"))); // NOI18N
        jbCarta16.setMaximumSize(new java.awt.Dimension(80, 80));
        jbCarta16.setMinimumSize(new java.awt.Dimension(80, 80));
        jbCarta16.setName("16"); // NOI18N
        jbCarta16.setPreferredSize(new java.awt.Dimension(120, 120));
        jbCarta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCeldasLayout = new javax.swing.GroupLayout(jpCeldas);
        jpCeldas.setLayout(jpCeldasLayout);
        jpCeldasLayout.setHorizontalGroup(
            jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCeldasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCeldasLayout.createSequentialGroup()
                        .addComponent(jbCarta13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCeldasLayout.createSequentialGroup()
                        .addComponent(jbCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCeldasLayout.createSequentialGroup()
                        .addComponent(jbCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jbCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCeldasLayout.createSequentialGroup()
                        .addComponent(jbCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpCeldasLayout.setVerticalGroup(
            jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCeldasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCarta6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCarta11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCarta12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCeldasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCarta14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCarta16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre Jugador:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Intentos:");

        jlIntentos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlIntentos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jpCeldas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTematica, 0, 181, Short.MAX_VALUE)
                            .addComponent(jtNomJugador)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcbTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtNomJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlIntentos))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpCeldas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta1ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta1, 1);
        }
    }//GEN-LAST:event_jbCarta1ActionPerformed

    private void jbCarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta2ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta2, 2);
        }
    }//GEN-LAST:event_jbCarta2ActionPerformed

    private void jbCarta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta3ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta3, 3);
        }
    }//GEN-LAST:event_jbCarta3ActionPerformed

    private void jbCarta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta4ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta4, 4);
        }
    }//GEN-LAST:event_jbCarta4ActionPerformed

    private void jbCarta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta5ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta5, 5);
        }
    }//GEN-LAST:event_jbCarta5ActionPerformed

    private void jbCarta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta6ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta6, 6);
        }
    }//GEN-LAST:event_jbCarta6ActionPerformed

    private void jbCarta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta7ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta7, 7);
        }
    }//GEN-LAST:event_jbCarta7ActionPerformed

    private void jbCarta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta8ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta8, 8);
        }
    }//GEN-LAST:event_jbCarta8ActionPerformed

    private void jbCarta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta9ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta9, 9);
        }
    }//GEN-LAST:event_jbCarta9ActionPerformed

    private void jbCarta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta10ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta10, 10);
        }
    }//GEN-LAST:event_jbCarta10ActionPerformed

    private void jbCarta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta11ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta11, 11);
        }
    }//GEN-LAST:event_jbCarta11ActionPerformed

    private void jbCarta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta12ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta12, 12);
        }
    }//GEN-LAST:event_jbCarta12ActionPerformed

    private void jbCarta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta13ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta13, 13);
        }
    }//GEN-LAST:event_jbCarta13ActionPerformed

    private void jbCarta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta14ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta14, 14);
        }
    }//GEN-LAST:event_jbCarta14ActionPerformed

    private void jbCarta15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta15ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta15, 15);
        }
    }//GEN-LAST:event_jbCarta15ActionPerformed

    private void jbCarta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta16ActionPerformed
        if (jugando) {
            jbEnabled(jbCarta16, 16);
        }
    }//GEN-LAST:event_jbCarta16ActionPerformed

    private void jbIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarActionPerformed
        voltearCartas();
        if ("Finalizar".equals(jbIniciar.getText())) {
            jbIniciar.setText("Nueva partida");
            jbIniciar.setMnemonic('N');
            jcbTematica.setEnabled(true);
            jtNomJugador.setEnabled(true);
            jlIntentos.setText("0");
            jugando = false;
        } else {
            jbIniciar.setText("Finalizar");
            jbIniciar.setMnemonic('F');
            jcbTematica.setEnabled(false);
            jtNomJugador.setEnabled(false);
            jlIntentos.setText("0");
            jugando = true;
            cartasDisp = cantCeldas;
            iniciaJuego(jcbTematica.getSelectedIndex());
        }
    }//GEN-LAST:event_jbIniciarActionPerformed

    private void jbCarta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCarta1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCarta1MouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCarta1;
    private javax.swing.JButton jbCarta10;
    private javax.swing.JButton jbCarta11;
    private javax.swing.JButton jbCarta12;
    private javax.swing.JButton jbCarta13;
    private javax.swing.JButton jbCarta14;
    private javax.swing.JButton jbCarta15;
    private javax.swing.JButton jbCarta16;
    private javax.swing.JButton jbCarta2;
    private javax.swing.JButton jbCarta3;
    private javax.swing.JButton jbCarta4;
    private javax.swing.JButton jbCarta5;
    private javax.swing.JButton jbCarta6;
    private javax.swing.JButton jbCarta7;
    private javax.swing.JButton jbCarta8;
    private javax.swing.JButton jbCarta9;
    private javax.swing.JButton jbIniciar;
    private javax.swing.JComboBox<String> jcbTematica;
    private javax.swing.JLabel jlIntentos;
    private javax.swing.JPanel jpCeldas;
    private javax.swing.JTextField jtNomJugador;
    private javax.swing.JTable jtRanking;
    // End of variables declaration//GEN-END:variables
}
